---


  - name: Ensure configured homebrew packages are installed.
    homebrew:
      name: "{{ item.name | default(item) }}"
      install_options: "{{ item.install_options | default(omit) }}"
      state: present
    loop: "{{ sysbasics_pkgs }}"

  - name: Install configured cask applications.
    homebrew_cask:
      name: "{{ item.name | default(item) }}"
      state: present
      install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
      accept_external_apps: "{{ sysbasics_cask_accept_external_apps }}"
    loop: "{{ sysbasics_desktop_pkgs }}"
