---


- name: Gather facts as regular remote user
  setup:
  become: no
  tags: always

- include: pkgs.yml
  tags: pkg

- include: zsh.yml
  tags: zsh

- include: vim.yml
  tags: vim

- include: homeshick.yml
  tags: homeshick
