---


- name: Gather facts as regular remote user
  setup:
  become: no
  tags: always

- include: "{{ansible_system}}_pkgs.yml"
  when: not skip_pkg_tasks
  tags: pkg

- include: zsh.yml
  tags: zsh

- include: homeshick.yml
  tags: homeshick

- include: vim.yml
  tags: vim

- include: git.yml
  tags: git

- import_tasks: flathub.yml
  tags: flatpak
  when: "ansible_pkg_mgr == 'atomic_container'"
